### ISSUE TITLE
asp.net assignment

### ISSUE THREAD

**Issue by ArasakaAdmin** [stefanbund/311#1]
Professor Bund,

Will the dropbox be available before class tomorrow? Can you give us a list of things you would like us to screenshot?

**Comment by stefanbund** [comment]
Yes and yes. You can simply take screenshots as evidence of what you have completed

From Stefan

**Comment by ArasakaAdmin** [comment]
Professor Bund,
What type of scantron should we bring: small of full size?

May I have the link to the dropbox?

**Comment by stefanbund** [comment]
Large size, drop box link is on blackboard

From Stefan

**Comment by ArasakaAdmin** [comment]
Professor Bund,

Do you have extended office hours today? Will you be close to 7PM?

**Comment by stefanbund** [comment]
I am in my office right now, until close to 8 PM

From Stefan

**Comment by ArasakaAdmin** [comment]
Professor Bund, 
Will you be in your office today?
