### ISSUE TITLE
Micro Project 1

### ISSUE THREAD

**Issue by bdperea** [stefanbund/311#11]
For the YouTube Video is it alright if we have no audio on it? I don't have any working equipment.

And for the project itself, do you want us to code the pages and make a YouTube video of 3 separate web pages, where I display the code and show how it works, or are we suppose to make 1 website with 3 web pages?

**Comment by stefanbund** [comment]
No audio right now is all right. Think of it as three separate pages that share one very general idea.

From Stefan Bund
