### ISSUE TITLE
Stuck...   (solved)

### ISSUE THREAD

**Issue by PatrickMinett** [stefanbund/311#12]
I created a simple function to get the users input and test it. For whatever reason I cant get it to output the results..... any ideas?

Code: 

<DOCTYPE html>
<html>

<head> 
<title> Page 1 First Battle of Bull Run</title>

<body>   

<h1> First Battle of Bull Run </h1>

<p> Histocal background of the battle here </p>

<p> recommend sites to vist </p>

<p> recommend videos </p>

<p> recommend Books </p>

<p> recommend Games </p>

<p> recommend Maps</p>

<h4> Test your knowloge of First Bull run! <h4>

<p> What year did the battle of first bull run take place? <p>

<input Id = resp Type = text>

<button type="button" onclick="myFunction()">Submit answer</button> 

<p Id = "output"> </p>

<script>
fucnction myFuction() 
{
Var x,y

x = document.getElementById("resp").text;

If ( x = 1861) 
{

y = "Wow good job you are correct!";

} else { 

y = "Sorry that is incorrect";

}

Document.getElementById("output").innerHTML =  y

}               

 </script> 

</body>
</html>

**Comment by stefanbund** [comment]
var x, y

Needs to be terminated with the;

From Stefan Bund

**Comment by PatrickMinett** [comment]
Still not outputting anything. Also noticed I used text instead of number which made no sense seeing as I was asking for a year not a string.

**Comment by PatrickMinett** [comment]
Turns out if <--- was if which is If, which is incorrect. I am still having trouble getting the logic to work correctly but at the very least its outputting now.

Edit: was able to fix it.... seems a need to review my basic java (x = 1861) was causing the logic to default to the first y output. After correctly the issue ie (x == 1861) all is working correctly.

**Comment by stefanbund** [comment]
Give me two in the parentheses, the comparison operator should read

X ==



From Stefan Bund
