### ISSUE TITLE
Micro Project 1 

### ISSUE THREAD

**Issue by robertoh123** [stefanbund/311#13]
Hello Professor 

For the three webpages what would you like us to include?

**Comment by stefanbund** [comment]
Naturally, read the syllabus related to the micro project. It outlines what you must do each week. The gist is that you must do something related to the source code and unit one. Interpret it for your own needs, according to your own business idea, then demonstrate, in your video, how you used it.

From Stefan Bund

**Comment by robertoh123** [comment]
Where would you like us to attach the link to our blog?

**Comment by stefanbund** [comment]
You will submit the URL during class on Tuesday, I will provide you a website where you can do so. Thank you for asking about this

From Stefan Bund
