### ISSUE TITLE
How to pass user input to an object?

### ISSUE THREAD

**Issue by PatrickMinett** [stefanbund/311#17]
I tried: 

function objectBuild(firstName,lastName,corps){

var x,y,z;

x = document.getElementById("genfirstname").value;
y = document.getElementById("genlastname").value;
z = document.getelementById("gencorps").value;

this.firstName = x;

this.lastName = y;

this.corps  = z;

}

this did not work, so I then tried,

var commander = new objectBuild (x,y,z); // was hoping this would act like the example but with user info being pulled from the users input.

Finally I tried:

`<button type="button" onclick="objectBuild(firstName,lastName,corps)">Submit Answer</button>

<p id="output"></p>

<script>
function objectBuild(firstName,lastName,corps){

this.firstName = firstName;

this.lastName = lastName;

this.corps  = corps;

} 

var x,y,z;

x = document.getElementById("genfirstname").value;
y = document.getElementById("genlastname").value;
z = document.getelementById("gencorps").value;

var commander = new objectBuild ("x","y","z");

document.getElementById("output").innerHTML = " commander is name and corps is " + commander.firstName + " "+ commander.lastName +" "+ commander.corps;

</script> `

**Comment by stefanbund** [comment]
Just a comment on your first plan, when you run object build, you need to assign values to each parameter in the method signature, not through get Element by ID inside the function

From Stefan Bund
