### ISSUE TITLE
microproject 3

### ISSUE THREAD

**Issue by cis311** [stefanbund/311#18]
For micro project 3 
Is that due on Thursday or next Tuesday?
And do we still need to create 3 pages same as before?
Thx

**Comment by cis311** [comment]
Professor 
Btw. I did not use the JS for wk2 for micro project 2
Can I redo the micro2 as a late work
Thank you

**Comment by stefanbund** [comment]
Tuesday, just integrate the new skills into the existing pages, if that is convenient

From Stefan Bund

**Comment by stefanbund** [comment]
Sorry, no. With 60 projects rolling in per week the deadline is firm.

From Stefan Bund
