### ISSUE TITLE
Updating Error:  ERROR: NetworkingError: Network Failure

### ISSUE THREAD

**Issue by shiqidai1002** [stefanbund/311#2]
<img width="960" alt="error" src="https://cloud.githubusercontent.com/assets/22432937/19097960/cb6e28d6-8adb-11e6-9b03-2af40793e083.png">

**Comment by shiqidai1002** [comment]
I AM SORRY I DON'T KNOW WHY MY BROWSER IS CHINESE.

**Comment by stefanbund** [comment]
Please recheck your cors configuration for the tutorial page, then give an update

From Stefan

**Comment by stefanbund** [comment]
You are good, Chinese is supported in this class 😻

From Stefan

**Comment by shiqidai1002** [comment]
I MAKE IT! THANKS FOR YOUR TIPS! @stefanbund 

<img width="462" alt="success" src="https://cloud.githubusercontent.com/assets/22432937/19099192/9e2a6d2a-8ae6-11e6-93ab-a6b147d7e248.png">

**Comment by stefanbund** [comment]
Congratulations, you're a little tiny web developer

From Stefan
