### ISSUE TITLE
placing <div> tag inside a <p></p>

### ISSUE THREAD

**Issue by PatrickMinett** [stefanbund/311#20]
I am currently working on a page, and the page in question has a default layout which I would not like to change. I know in are example we sent the output of are script to the body tag. If I did it with my code it would ruin the layout of the page. In order to get around this I had the output of the script go to a <p> tag which seems to have worked. However, in my independent study I was told that this was bad practice and should not be done. So my question is should a div tag ever be inside a other html tag such as <p> or <h#>?

this is what my page structure looks like after the script is done:

<.p>
<.div>
<.h1>
some test
</.h1>
<.p>
text content
</.p>

</.div>

</.p>

From what I can tell everything is working just fine, debugger picks up no issues.

Thanks.

**Comment by stefanbund** [comment]
Sorry if my replies seems picky, but try to put the paragraph inside of the div, not the other way around.

From Stefan Bund

**Comment by PatrickMinett** [comment]
Always willing to improve, I thank you for the feed back. I ended up changing my output from:

<p id="output"></p> to <div id="output"></div> this way all the results will be place INSIDE a div not a paragraph.
