### ISSUE TITLE
Missing credentials in config when trying to quary db

### ISSUE THREAD

**Issue by PatrickMinett** [stefanbund/311#21]
message": "Missing credentials in config", "code": "CredentialsError", "time": "2017-01-30T22:30:10.380Z", "originalError": { "message": "No credentials to load", "code": "CredentialsError", "time": "2017-01-30T22:30:10.379Z" } }

not sure what I did wrong here, I followed the videos to the letter.

**Comment by stefanbund** [comment]
I will be able to do a walk-through tomorrow.

From Stefan Bund

**Comment by TatianaCis311** [comment]
I have the same error

**Comment by stefanbund** [comment]
Credentials error stems from two potential places. One is the URL you submitted to Facebook, which hosts to your page on AWS. The second is whether the table you added into your IAM role exists in dynamo. Then you must be sure that your code references the name of the table that you have and I a.m., assuming it is already in dynamo.

From Stefan Bund

**Comment by TatianaCis311** [comment]
Thanks,
I copied the URL from AWS to Facebook,
I modified Table name in the code to match my Table in DynamoDb,
 but I still have the error.
Do I have to add:  Access key ID, and  Secret access key ,as credentials, in order to access DynamoDb?

**Comment by stefanbund** [comment]
Tatiana, you won't need to code in your credentials, as you wrote. These two lines help your javascript connect to AWS and operate in an authenticated way:

var appId = '120636118298132'; //from facebook
var roleArn = 'arn:aws:iam::165021830876:role/spring2017Dynamodb'; //from AWS IAM

You also used Facebook's authentication code at the bottom of the example, which provide the login page (and thus the credentials you'll need, which actually come from FB)

**Comment by TatianaCis311** [comment]
Thanks;
I will show you my code in class...
