### ISSUE TITLE
I want to give vistors the ability to update my database.

### ISSUE THREAD

**Issue by PatrickMinett** [stefanbund/311#23]
I want to give visitors the ability to leave feed back on the site. I will get the following data from the Visitor :  first name, last name, email and short message. All of this data will be saved to a table called Message. 

How do I allow anyone to access my dynamodb?  

Is that even possible?

**Comment by stefanbund** [comment]
When you use the Amazon resource name, once they login to Facebook, they should be able to interact with your data

From Stefan Bund

**Comment by PatrickMinett** [comment]
Ah perfect. Thank you.
