### ISSUE TITLE
Having trouble connecting my pages togather.

### ISSUE THREAD

**Issue by PatrickMinett** [stefanbund/311#25]
I am useing what we learned about links this weekend to connect all my pages to my main page. all the pages work correctly when I click on them in s3, However, When I try to go from the main page (which has links to the other pages I get the following)
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>087C51862B6A5C10</RequestId><HostId>Z1Eb2GKnNIQVwW4FAzeYKVXAjzFd00wnHVtJBW9SaStmdCX29GTYEZxTBeSzzPOx3AA1xbL1PLo=</HostId></Error>

Not really sure what I did wrong.

A sample of the syntax used 

<p> <a href=https:"https://s3-us-west-2.amazonaws.com/cis311acwp/Armory.html">Check out our armory of weapons!</a> </p> 

any suggestions?

thanks.

**Comment by PatrickMinett** [comment]
oh I caught the issue, It would appear that for whatever reason I wrote two http's in the code.  After removing one the problem was solved.

thanks again.

**Comment by stefanbund** [comment]
There might be a slash that is getting the way of resolving the URL parameters. Show me the URL you used that is failing. 

From Stefan Bund
