### ISSUE TITLE
Storing more then one set of values in a cookie.

### ISSUE THREAD

**Issue by PatrickMinett** [stefanbund/311#26]
Hi, I am trying to store 2 values that the user provides, however  I am having trouble getting this to work. 

I believe the error is happening in the setCookie function:

// we are setting the users name and age.

function setCookie(cname,cvalue1,cage,cvalue2,exdays) {  
    var d = new Date();
    d.setTime(d.getTime() + (exdays*24*60*60*1000));
    var expires = "expires=" + d.toGMTString();
    document.cookie = cname+"="+cvalue1+";"cage+"="+cvalue2+";"+expires;
}

two questions, Can I actually store more then 1 value in a cookie? If so do you see anything wrong with my syntax?

**Comment by stefanbund** [comment]
Interesting let's take a look during class tomorrow

From Stefan Bund

**Comment by stefanbund** [comment]
I encourage everyone to take the safe route, and employ very simple, very low risk code that fires on every occasion. Embedding only one value per key/value pair in document.cookie is a technique like this

**Comment by PatrickMinett** [comment]
Makes sense, I ended up doing just that.  I went ahead and created 3 separate cookies which ended up giving me my desired result. 

Thanks for the help.

**Comment by stefanbund** [comment]
👏🏻

From Stefan
