### ISSUE TITLE
App Domain issue

### ISSUE THREAD

**Issue by ryanohara7** [stefanbund/311#4]
Hi Professor, I'm having issues with the app domain. 

![image](https://cloud.githubusercontent.com/assets/22380472/19132628/63d9ee98-8b09-11e6-976d-5c643a84f532.png)

![image](https://cloud.githubusercontent.com/assets/22380472/19132643/76928ea0-8b09-11e6-87c5-cab4efa8f7cc.png)

**Comment by stefanbund** [comment]
it appears that your domain contains the actual link, fully resolved, to your file. It should be empty like so

**Comment by ryanohara7** [comment]
thanks professor! i got it working i think

![image](https://cloud.githubusercontent.com/assets/22380472/19135459/846f5656-8b19-11e6-84d0-61b8941d4dfa.png)
