### ISSUE TITLE
DynamoDB Missing Credentials

### ISSUE THREAD

**Issue by ScottLuttrell** [stefanbund/311#6]
I disabled the cache like we discussed and that fixed the issue I was having in class. Now I am having this problem...

![image](https://cloud.githubusercontent.com/assets/22380465/19624307/8f53a8ae-98a4-11e6-9961-d3b224145cb3.png)

**Comment by jeff93** [comment]
I'm having the same issue. Tried reconfiguring CORS and Policies but that didn't help. Also tried recreating the dynamo table, no luck. Also updated the src script header at the top of the javascript to the newest SDK available, but that didn't help. I'm running out of ideas and google searching hasn't given me the right answers. 

Also, it's wierd how running the upload s3 javascript gives me the same error, but allows me to upload anyway.

**Comment by stefanbund** [comment]
When you were doing a put, make sure that the value put in the attributes box is the same as the attribute you have in your table. Let's talk about it tomorrow, then we can probably wrap this one up

From Stefan
