### ISSUE TITLE
Listing bucket items

### ISSUE THREAD

**Issue by pfftdammitchris** [stefanbund/311#8]
Professor,  in my project, I want to list the bucket objects immediately after authenticating and before we click anything. The way your code example is showing me is that its coded to display the list after clicking/uploading a file. 

I tried calling the bucket.listObjects() function to display without clicking anything but it is not displaying any results

**Comment by stefanbund** [comment]
For Checotah pier, I hope you have declared an S3 object that helps you address the bucket

From Stefan
