### ISSUE TITLE
dynamodb

### ISSUE THREAD

**Issue by marioiturralde** [stefanbund/311#9]
Professor,

can you please provide the code to store a user input text area to dynamodb so that it can permanently be on webpage for everyone to see. I managed to get it to work using local storage but everyone cannot see that content. ex. http://jsfiddle.net/Xh2En/24/

**Comment by stefanbund** [comment]
JS fiddle is an amazing resource, but you will have to place your webpage and its JavaScript within your S3 bucket to get visibility for everyone. 

From Stefan
